version: "3.2"

services:
  mariadb:
    image: mariadb:10
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"
    networks:
      - hunter
    volumes:
      - "mariadb-data:/var/lib/mysql"

  redis:
    image: redis:5-alpine
    restart: always
    networks:
      - hunter
    ports:
      - "6379:6379"

  traefik:
    image: traefik:v2.6
    container_name: Traefik
    restart: always
    command:
      - --log.level=INFO
      - --api=true
      - --api.dashboard=${APP_DEBUG}
      - --providers.docker
      - --providers.docker.exposedByDefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entryPoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      # ACME
      - --certificatesresolvers.primary.acme.httpchallenge=true
      - --certificatesresolvers.primary.acme.email=${TRAEFIK_ACME_EMAIL}
      - --certificatesresolvers.primary.acme.storage=acme.json
      - --certificatesresolvers.primary.acme.httpchallenge.entrypoint=web
    ports:
      - ${TRAEFIK_HTTP_PORT}:80
      - ${TRAEFIK_HTTPS_PORT}:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme/acme.json:/acme.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=websecure"
      # Uncomment to enable HTTPS via ACME
      - "traefik.http.routers.api.tls.certResolver=primary"
    networks:
      - hunter
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"

  hunter-web:
    build: ./build
    #image: simplyunnamed/eve-hunter:latest
    container_name: hunter_web
    networks:
      - hunter
    command: web
    env_file:
      - .env
    depends_on:
      - traefik
      - mariadb
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hunter-web.rule=Host(`${APP_ADDRESS}`)"
      - "traefik.http.routers.hunter-web.entrypoints=websecure"
      # Uncomment for HTTPS
      #- "traefik.http.routers.hunter-web.tls.certResolver=primary"


  hunter-worker:
    #build: .
    image: simplyunnamed/eve-hunter:latest
    container_name: hunter_worker
    networks:
      - hunter
    command: worker
    env_file:
      - .env
    depends_on:
      - hunter-web
      - mariadb
      - redis

  hunter-cron:
    #build: .
    image: simplyunnamed/eve-hunter:latest
    container_name: hunter_cron
    networks:
      - hunter
    command: cron
    env_file:
      - .env
    depends_on:
      - hunter-web
      - mariadb
      - redis

networks:
  hunter:

volumes:
  mariadb-data:
