name: Build NodeJS Files

on:
  push:
    branches: 
      - master

jobs:
  build_an_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - name: Clean Install and build
        run: |
          npm ci
          npm run build
      - name: Create Docker Image
        run: docker build . --file ./build/Dockerfile --tag eve-hunter-app:$(date +%s)
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          repository: simplyunnamed/eve-hunter
          tags: latest, ${{ github.run_number }}

