name: Build NodeJS Files

on:
  push:
    branches:
      - master

jobs:
  build_an_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_VITE_PUSHER_HOST: ${{ secrets.PUSHER_HOST }}
          envkey_VITE_PUSHER_APP_KEY: ${{ secrets.PUSHER_APP_KEY }}
          envkey_VITE_PUSHER_PORT: ${{ secrets.MIX_PUSHER_PORT }}
      - name: do a thing
        run: cat .env
      - name: Clean Install and build
        run: |
          npm ci
          npm run build
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./build/Dockerfile
          push: true
          tags: simplyunnamed/eve-hunter:latest, simplyunnamed/eve-hunter:${{github.run_number}}

